
# version: 2

# models:
#     - name: my_first_dbt_model
#       description: "A starter dbt model"
#       columns:
#           - name: id
#             description: "The primary key for this table"
#             tests:
#                 - unique
#                 - not_null

#     - name: my_second_dbt_model
#       description: "A starter dbt model"
#       columns:
#           - name: id
#             description: "The primary key for this table"
#             tests:
#                 - unique
version: 2

sources:
  - name: raw
    database: ECOMMERCE_DB      # ← for ecommerce models
    schema: raw
    tables:
      - name: orders_raw

  - name: raw_epiclim
    database: EPICLIM_DB        # ← for epiclim models
    schema: raw
    tables:
      - name: epiclim_raw

  
# models:
#   - name: stg_orders
#     description: "Cleans and formats the raw eCommerce orders data"
#     columns:
#       - name: invoice_no
#         description: "Invoice number for the transaction"

#   - name: fct_customer_revenue
#     description: "Aggregated metrics per customer based on their order history"
#     columns:
#       - name: customer_id
#         tests:
#           - not_null
      
#       - name: total_orders
#         description: "Total number of invoices/orders"
#       - name: total_revenue
#         description: "Total revenue generated by the customer"
#       - name: first_order_date
#         description: "First purchase timestamp"
#       - name: last_order_date
#         description: "Most recent purchase timestamp"
    # -name : stg_epiclim

models:
  - name: stg_epiclim
    description: "Staging model that cleans, casts, and prepares raw epidemic + climate data"
    columns:
      - name: week_label
        description: "Formatted week indicator"
        tests: [not_null]
      - name: state
      - name: district
      - name: disease
        tests: [not_null]
      - name: cases
      - name: deaths
      - name: outbreak_date
        description: "Date of the outbreak (built from year/month/day)"
      - name: temperature_k
      - name: precip_mm

  - name: fct_disease_metrics
    description: "Aggregated disease and climate metrics by location and week"
    columns:
      - name: week_label
        description: "Week of outbreak (used as grouping key)"
        tests: [not_null]
      - name: state
      - name: district
      - name: disease
        description: "Disease being tracked"
        tests: [not_null]
      - name: total_cases
        description: "Total number of disease cases in that week/location"
      - name: total_deaths
      - name: avg_temperature_k
      - name: avg_precip_mm
      - name: outbreak_count
        description: "Number of individual records grouped into this summary"