
# version: 2

# models:
#     - name: my_first_dbt_model
#       description: "A starter dbt model"
#       columns:
#           - name: id
#             description: "The primary key for this table"
#             tests:
#                 - unique
#                 - not_null

#     - name: my_second_dbt_model
#       description: "A starter dbt model"
#       columns:
#           - name: id
#             description: "The primary key for this table"
#             tests:
#                 - unique
#                 - not_null
version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: orders_raw

models:
  - name: stg_orders
    description: "Cleans and formats the raw eCommerce orders data"
    columns:
      - name: invoice_no
        description: "Invoice number for the transaction"

  - name: fct_customer_revenue
    description: "Aggregated metrics per customer based on their order history"
    columns:
      - name: customer_id
        tests:
          - not_null
      
      - name: total_orders
        description: "Total number of invoices/orders"
      - name: total_revenue
        description: "Total revenue generated by the customer"
      - name: first_order_date
        description: "First purchase timestamp"
      - name: last_order_date
        description: "Most recent purchase timestamp"
